In [ ]:
!pip install pandas
import pandas as pd

# 1. Cargo el archivo JSON en la carpeta raw
df = pd.read_json("../data/raw/streaming_users_dirty.json")

# 2. Le pido a la computadora que nos muestre las primeras filas
df.head()

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\estudiante\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\estudiante\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.8 MB 3.3 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.8 MB 3.6 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/9.8 MB 4.6 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.8 MB 5.0 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.8 MB 4.6 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.8 MB 4.6 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.8 MB 4.4 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.8 MB 4.2 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.8 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 3.5 MB/s eta 0:00:00
Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 2.4 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.4 MB 2.5 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/12.4 MB 2.4 MB/s eta 0:00:05
   ------ --------------------------------- 2.1/12.4 MB 2.4 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.4 MB 2.3 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.4 MB 2.1 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.4 MB 1.9 MB/s eta 0:00:05
   ---------- ----------------------------- 3.1/12.4 MB 1.9 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.4 MB 1.8 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.4 MB 1.8 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.4 MB 1.8 MB/s eta 0:00:05
   -------------- ------------------------- 4.5/12.4 MB 1.8 MB/s eta 0:00:05
   ---------------- ----------------------- 5.0/12.4 MB 1.7 MB/s eta 0:00:05
   ---------------- ----------------------- 5.0/12.4 MB 1.7 MB/s eta 0:00:05
   ---------------- ----------------------- 5.2/12.4 MB 1.6 MB/s eta 0:00:05
   ----------------- ---------------------- 5.5/12.4 MB 1.6 MB/s eta 0:00:05
   ------------------ --------------------- 5.8/12.4 MB 1.6 MB/s eta 0:00:05
   ------------------- -------------------- 6.0/12.4 MB 1.5 MB/s eta 0:00:05
   -------------------- ------------------- 6.3/12.4 MB 1.5 MB/s eta 0:00:05
   --------------------- ------------------ 6.6/12.4 MB 1.5 MB/s eta 0:00:04
   --------------------- ------------------ 6.8/12.4 MB 1.5 MB/s eta 0:00:04
   ----------------------- ---------------- 7.3/12.4 MB 1.5 MB/s eta 0:00:04
   ------------------------ --------------- 7.6/12.4 MB 1.5 MB/s eta 0:00:04
   ------------------------- -------------- 7.9/12.4 MB 1.5 MB/s eta 0:00:04
   -------------------------- ------------- 8.1/12.4 MB 1.5 MB/s eta 0:00:03
   --------------------------- ------------ 8.4/12.4 MB 1.5 MB/s eta 0:00:03
   --------------------------- ------------ 8.7/12.4 MB 1.5 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.4 MB 1.5 MB/s eta 0:00:03
   ----------------------------- ---------- 9.2/12.4 MB 1.5 MB/s eta 0:00:03
   ------------------------------- -------- 9.7/12.4 MB 1.5 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 1.5 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.5 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.4 MB 1.5 MB/s eta 0:00:02
   ----------------------------------- ---- 11.0/12.4 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 1.5 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 1.5 MB/s eta 0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.1 pandas-3.0.3 tzdata-2026.2

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,10000,39,Estándar,805.8,Brasil,Crime,2025-03-04,99
1,10001,37,Estándar,1173.4,Colombia,Crime,2019-04-02,2
2,10002,28,Básico,401.0,Colombia,Crime,2018-04-13,0
3,10003,43,Básico,62.4,Uruguay,Thriller,2021-01-31,0
4,10004,51,Básico,477.8,Perú,Thriller,2020-09-30,1

In [3]:
# 3. Ver el tamaño total (filas y columnas)
print("--- TAMAÑO DEL DATASET ---")
print(f"Filas: {df.shape[0]} | Columnas: {df.shape[1]}\n")

# 4. Ver qué columnas hay y si tienen datos nulos/vacíos
print("--- INFORMACIÓN GENERAL Y VACÍOS ---")
df.info()

--- TAMAÑO DEL DATASET ---
Filas: 8160 | Columnas: 8

--- INFORMACIÓN GENERAL Y VACÍOS ---
<class 'pandas.DataFrame'>
RangeIndex: 8160 entries, 0 to 8159
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8160 non-null   int64
 1   age                       8160 non-null   int64
 2   subscription_plan         8160 non-null   str
 3   monthly_watch_time_mins   7967 non-null   float64
 4   country                   8160 non-null   str
 5   favorite_genre            7920 non-null   str
 6   last_login_date           7840 non-null   str
 7   customer_support_tickets  8160 non-null   int64
dtypes: float64(1), int64(3), str(4)
memory usage: 510.1 KB

In [4]:
# Ver estadísticas básicas de las columnas numéricas (edad, tiempo, tickets de soporte)
df.describe()

,user_id,age,monthly_watch_time_mins,customer_support_tickets
count,8160.000000,8160.000000,7967.000000,8160.000000
mean,13995.433824,34.096814,1107.346153,1.800980
std,2310.810660,14.511304,5310.442604,11.334969
min,10000.000000,-5.000000,-120.000000,-1.000000
25%,11987.750000,25.000000,489.200000,0.000000
50%,13998.500000,33.000000,757.400000,1.000000
75%,15997.250000,42.000000,1045.700000,1.000000
max,17999.000000,150.000000,99999.000000,150.000000